# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 929124b0138f065d60d1a204e6a47cdc520115db4b3e8c47f7c7376737eb8905de8fce00ab55b057f59c9d15c49eba3d303c823397386cc79368146dcbb45a82

test:
  secret_key_base: f972397e29bcedd4205218c3cfaadf4baa5da46a7a0e45fa2708ab287e62362aa84c785f641206fa63c0659a4f90645e8460af31a3115ec6be9b3af3a5cca47d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
